version: '3.8'
services:
  app:
    build: .
    container_name: my_node_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=testdb
  
  db:
    image: mysql:8.0
    container_name: my_mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=testdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: